---
- hosts: all
  name:  configure VLAN service
  tasks:
  - include_vars: 
      file: "{{inventory_dir}}/services.yml" 
      name: services
  - set_fact: data="{{lookup('template','templates/node-model.j2')}}"
  - nxos_vlan:
      provider: "{{cli}}"
      vlan_id: "{{item.key}}" 
      name:    "{{item.value}}"
      state:   "present"
      admin_state: "up"
    with_dict: "{{data.vlans}}"

  - nxos_interface:
      provider: "{{cli}}"
      admin_state: up
      interface:   "{{item.key}}"
      mode:        layer2
    with_dict: "{{data.ports}}"

  - nxos_switchport:
      provider: "{{cli}}"
      mode:        access
      access_vlan: "{{item.value}}"
      interface:   "{{item.key}}"
    with_dict: "{{data.ports}}"